// Generated by tools/generate_fonts.sh — do not edit by hand.
//
// Font Awesome 6 Free (Solid), subset to the icons used by this plugin.
// Font: SIL OFL 1.1. Icons: CC BY 4.0. Copyright Fonticons, Inc.
// Source: github.com/FortAwesome/Font-Awesome (6.7.2)

#pragma once

// File: 'fa_subset.ttf' (4124 bytes)
// Exported using binary_to_compressed_c.exe -base85 "fa_subset.ttf" fa_solid
inline const char fa_solid_compressed_data_base85[3630+1] =
    "7])#######O+Y$,'/###[),##-`($#Q6>##kZn42T51D?4C/2'3@'o/aNV=BApt$Lc(m<-8sEn/%/0%J$>K`=1MPH203NP&Z.d<Bu%`r*e<jl&-KVX-TT$=(Dhlb#3?:@-_qEn/<_[FH"
    ")hM7#14S>-isEn/Y2JuB//PJ,E)m<-^rEn/=I[^IoZV<%Y)m<-Q&g<6+>00FfO:15OMJM'3->>#e%S+Hwcg:#KUfi'GmIJMlbcA#El7-#rkPA5[Emh2qNbc2@f)T/,'w)4M2'J3`Y*f2"
    "lc6F%gsD-&6+<5&sbo/Lj5p*%q*^DMLJmu>%f0#vaOf/L2nis%59o2&vpuw.dO5;-a%<e?X4a$'@m<i2+Y<9/wHx8%^^#pLhl@d)4E)a-;c6F%q^D.3/mTI*VcYs-E@%lLN54D#/0jE-"
    "2+6D-MY2X-Sf+6+VZi'#1oUvu0GAX#Di7-#dFII-]0RE.jpB:%7ig;%.x(t-dI+gLK2KgL5YOjLIxMT/+XqS/MXP8//hq8/FO@lLdh+G4_PlD4r*w^]_5#H3Z0ihL,:_F*HeN.N+F5gL"
    "-M_lLjU=U%@HoT$^qmY#eC[8%G0pm&2TAM)Z<5j'#S'f)YPsa*2&`6&GXEp%P#PZ-HlU)/eU<p%a6Re*?8rL16>Sj0Us^6&raP3'pVQN'_mu/(ST1g(/qZS'1cCv#/D*0(SNuj'^;7L("
    "qL=6'Waa8&(kOZ-ij4(/]_AP#mCaT/40pG25e+/(D7b.q^:4;6MM'##28r&M%1+f2Kon;%7%Is-:rUkLW#nh2MD^+4v#]3%'sse)(oA:/OX5gLN?]s$0WP,*pYs$'u>.H)LJqJ)^D+o$"
    "nfTI*ohR,*sZwr7du773^f)T/9]<B-TKDA.sf6<.gn#=.ms&x&D'9Z7@M+Q'%,TV--$0+%4NBj(a5p0#cn(3(>nJm&LbeW$$ARs$8Xjp%p7?]P@imY#@#x6.WgIO(`ELe$OfS<.(,*O'"
    "<SMt.VE^4MRa/)$8o1?#:vdg-_M9cN>J-##'&>uuiA3L##Lb&#APj)#/%(,)=qlh2sYHe2/mLH*62pb4HpG0l=%bBoa(?LM['ZV-Vlne2j:*T/Z8c8.P50J3[AOw$ObA:/c.W=._NneM"
    "t7>c487N`+[hL`+8_W>-Rl=gL*SG]uZ+>uu/ufcM*^cA#Xvx?#39b2(6H]C&,o'hLLH*^-XX_w9_+sV7#]kA#<m6]-0p5C&j#u1qfTu-$0Bqi'8psH?ri[+MRV/GV@%$##Qpme2nHjR8"
    "4q&g2trwv-Ckjp%#3<QUI5BlYpl,W-NMlw'@L+%'s&OuMNV:@MHD$##gH#/L4a:m=`>OT'Jb0g2g)EE-X#t#.GdlhMSpL4fYxl;-'OJF-(RJF-6`P.95t2KV&,###idcfL1B=A+/PNY5"
    "_)dA4HsJF4>VuP8a/)^m,OL+*#V^F*wpo8%(r-lLJ2@a39e8J3BV'f)hCh8.s^v)4O+va5q;Lv-WTPS9D/d,*lN-.MSDK88Q@T9V]kZV-WQpV8W$:#.2,I`&4$;)*s^FkLjmY18TS_,F"
    "h(jR#2g[%#bSi3XXv8.*U8.bRv4:W-W+_E[a`>>#dZ4A#M/]h('fPW-q-&(&A&wx'@OG&#+?-Lu(D4siQZ.'#%&>uu6Va-ZMV:ppjMJF4.W=P(L^2[-nn+>%S?hg2R3,S9c%vG*/_/:`"
    "S`kC#a0P<L>W<T'-gh-2n<;O'^w)ROJG3U-Jrtv-XqV2MX9GbFIqP&#ao:]0g5wK#V)+&#hY_U8%QQeQu=*x-0aS+4k)0i)'R)i2KRAQCTtAOTKuXs3c.]h(gKFq%diBCLvD0XV*bG>#"
    "Rp=5SgU@`afp=2L1%<T.Vakp%G87M.$U9>#MZx;-t:ds-SxefLo1Sr#p@)4#gvK'#n$(,)dhK,3%Mte)vk[s$f:Bbe>J,G4]Ul3+f*PZ.)4L+*:n_Trai?<.Vk9?-$RUo7>rRgE3rOo7"
    "H^8:)DK4<-tNP%M69QwLwF&(%,..kX3wU&#-mMY$V+V$#jasn%CKu(3mar;%/NF03?\?%/&mk]U/,[[I-,K;u2?b_F*&W*i2OV>c4w$&9%JsWhPP^KF%&mZp%xW'r%hFsIL$)wILUKlN'"
    "NQUO'H[R@#q;ugLfubP8sSkQ'GqOJ(Q9X>)*5pr-wgTx7u(kCl[3k+VBa?D*JC$##8/qR/XR+f28u8L(6lsj$@`/x$j/Z]4N@Je27,d5/(D>c4=px$ME>slKD.D?#n]KiuGfefQ5W_s-"
    ":]Gc41Dr_u($o+M$Gs+MiFw8%E,f&(7:]lJ&+5`uZopfLgG>D<98###51%wuAW+Q#qqm(#&%(,)q@34:m'pG3dRjEI)M4gL9R^C4=7c8/uuTL&qRNT/,EN$%'+1f)7[]jM$4_F*2R2Y$"
    "5/ck2>K%v5JV7)6,Q=;-s_qp$kjeB5NEoY-5e]jMd##]#E^p&-'1,Q'hP?4M+#Rx-GdT49Jxc,*Mm&gMUP>CL<>&]#oPBI$X-/W-d$N9`ipK]=*`$s$'au^Zc5H':m8^;.][m.'wB;wg"
    ")omm8]9kM(uC<:ik'tm)l^oN0_IIp.oWf-)DmnNOkt^IqtK]@#t#=u-FLn'&pKQB#V1C((&X7k9Emn&GNo7,)ao_Q9Bs9^YltWp%7@vjtu?l056pYXNIsb0Ml(PS7I=/v$T-Fkko]2GV"
    "=[CP8*ogT/9i<<%ipo8%(,-W-cI8@'#q4QUEPFjLkY5V/p'Cg2Tl(?#[Kmh2-l@pgE8xiLoc2w$%ROjb3Gj(+c4[S%c,_S'i,Cq%et;'OD-PJ(D_9Q&F(w%-)QrFMAg.^#>D7T%l%(c'"
    ".R[c;_i#=&T*Fp%n3*33ZEl/(G`TY&vFr/;We%@#NG#SRV%M<-*RmxLeA::%>;_hLAXPHMo*&T%KBF]F-=#>Y(`XS7n-YoeC]T8.iN;Jhj8OAF<gGm&.dfci$&###2VP##b=qtOodPir"
    "0P5##XR-#mHSwVNF;&crg>W]O,wbw''DFcMe=?>#f5YG-:nL5/qL'^#]XbgLXE&@#lUjV7QW[w'slRfL6]#<-_@HeNTTx>-;+m<-5b%Y-/Y.R3vF$M^P`%/L)3hfrExIX($kj1#c+;;$"
    "Z=FGM)at?0NT[fC(h1m90[3N02h[%#T6YY#]=ffL6;K;-D.T,MA=_&?D=l.LrH:n[9J)qL.8KnL3xSfLKC?>#B4.#MB2oiLL@$##%#####G5s-j4FGM0`/%#J+PwL#dl&#,+ST%MMdK'"
    "92/q-0E+w=%ZIBE5v5e(XI*n@20m#tv*'*rq==n[#),##<ew*/Q4cdrlX*wl#_eQ]2b'hU&_r&t]L_T[1)S**GF$[,PKDNB$ZjBJD7m;%Yg2eZ)SFgL#V$lL:K8$MS@-##fo:.NaF6##"
    "pFW3NUL?##X.^4N2'IAOpXQ##hO<;NikZ##c=r$#XY<rLM?s/#TH4.#HB+.#c:F&#Y#S-#KM#<-'r.>-Mrw6/1G_/#)sarLBX+rLPTAu-SilLMnwXrLN(8qLxf>oLbRxqLU8^-#M,`26"
    "HhxK>WJR]4Fr@-dv];e?kQvQNv:r?TPRTq)]Sr%4iP0K28f3>5W#^G3TjA,3I41kbhN*vHOns]5Px_D4%*0@BJe(DNQT3U-#@reM(wiEOn^R+%#PK:#$?T2#X-oj0=o*##";

