#!/usr/bin/env python3
"""Build data/coastlines.dat and data/cities.dat from Natural Earth (public domain).

Coastlines and country borders come from the 1:50m set — enough for orientation at
world scale — while lakes use 1:10m, because inland water is what a VFR pilot
recognises and 50m renders Lake Geneva as a 15-point blob. Populated places use 1:10m
too: 50m holds only capitals, so a Zurich-Paris leg would show two labels.

Usage: python3 tools/build_map_data.py [output_dir]
"""
import json
import sys
import urllib.request

BASE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson"
SOURCES = [("C", "ne_50m_coastline"), ("L", "ne_10m_lakes"),
           ("B", "ne_50m_admin_0_boundary_lines_land")]
NESTING = {"LineString": 1, "MultiLineString": 2, "Polygon": 2, "MultiPolygon": 3}


def rings_of(geojson):
    """Flatten any geometry type down to lists of [lon, lat] pairs."""
    rings = []

    def walk(coords, depth):
        if depth == 1:
            rings.append(coords)
        else:
            for part in coords:
                walk(part, depth - 1)

    for feature in geojson["features"]:
        geometry = feature["geometry"]
        walk(geometry["coordinates"], NESTING[geometry["type"]])
    return rings


def build_cities(out_path):
    """Populated places as '<pop>|<lon>|<lat>|<name>', biggest first.

    Sorted by population so the renderer can simply take the first N that fall inside
    the view: the label count then stays readable at any zoom without a threshold table.
    """
    print("fetching ne_10m_populated_places_simple...", file=sys.stderr)
    url = f"{BASE}/ne_10m_populated_places_simple.geojson"
    with urllib.request.urlopen(url) as response:
        data = json.load(response)

    places = []
    for feature in data["features"]:
        name = (feature["properties"].get("name") or "").strip()
        population = feature["properties"].get("pop_max") or 0
        lon, lat = feature["geometry"]["coordinates"][:2]
        # Unnamed or population-less entries would render as anonymous dots.
        if name and population > 0:
            places.append((int(population), float(lon), float(lat), name))
    places.sort(reverse=True)

    lines = [
        "# Populated places for the xp_pilot track map.",
        "# Generated by tools/build_map_data.py - do not edit by hand.",
        "# Source: Natural Earth 1:10m populated places (public domain).",
        "# Format: '<population>|<lon>|<lat>|<name>', largest first.",
        "",
    ]
    lines += [f"{pop}|{lon:.4f}|{lat:.4f}|{name}" for pop, lon, lat, name in places]
    with open(out_path, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"  {len(places)} places -> {out_path}", file=sys.stderr)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "data"
    out_path = f"{out_dir}/coastlines.dat"
    lines = [
        "# Coastlines and lakes for the xp_pilot track map.",
        "# Generated by tools/build_coastlines.py — do not edit by hand.",
        "# Source: Natural Earth (public domain), coastline 1:50m, lakes 1:10m.",
        "# Format: '<C|L> <point count>' followed by that many '<lon> <lat>' lines.",
        "# C = coastline (open line), L = lake (closed ring), B = country border (open line).",
        "# Degrees, 4 decimals (~11 m).",
        "",
    ]

    for tag, name in SOURCES:
        print(f"fetching {name}...", file=sys.stderr)
        with urllib.request.urlopen(f"{BASE}/{name}.geojson") as response:
            rings = rings_of(json.load(response))
        # A ring under three points cannot enclose or outline anything worth drawing.
        rings = [r for r in rings if len(r) >= 3]
        print(f"  {len(rings)} parts, {sum(len(r) for r in rings)} points", file=sys.stderr)
        for ring in rings:
            lines.append(f"{tag} {len(ring)}")
            lines.extend(f"{lon:.4f} {lat:.4f}" for lon, lat in ring)

    with open(out_path, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}", file=sys.stderr)

    build_cities(f"{out_dir}/cities.dat")


if __name__ == "__main__":
    main()
