#!/usr/bin/env python3
"""Build data/coastlines.dat from Natural Earth (public domain).

Coastlines come from the 1:50m set — enough for orientation at world scale — while
lakes use 1:10m, because inland water is what a VFR pilot recognises and 50m renders
Lake Geneva as a 15-point blob.

Usage: python3 tools/build_coastlines.py [output_path]
"""
import json
import sys
import urllib.request

BASE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson"
SOURCES = [("C", "ne_50m_coastline"), ("L", "ne_10m_lakes")]
NESTING = {"LineString": 1, "MultiLineString": 2, "Polygon": 2, "MultiPolygon": 3}


def rings_of(geojson):
    """Flatten any geometry type down to lists of [lon, lat] pairs."""
    rings = []

    def walk(coords, depth):
        if depth == 1:
            rings.append(coords)
        else:
            for part in coords:
                walk(part, depth - 1)

    for feature in geojson["features"]:
        geometry = feature["geometry"]
        walk(geometry["coordinates"], NESTING[geometry["type"]])
    return rings


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "data/coastlines.dat"
    lines = [
        "# Coastlines and lakes for the xp_pilot track map.",
        "# Generated by tools/build_coastlines.py — do not edit by hand.",
        "# Source: Natural Earth (public domain), coastline 1:50m, lakes 1:10m.",
        "# Format: '<C|L> <point count>' followed by that many '<lon> <lat>' lines.",
        "# C = coastline (open line), L = lake (closed ring). Degrees, 4 decimals (~11 m).",
        "",
    ]

    for tag, name in SOURCES:
        print(f"fetching {name}...", file=sys.stderr)
        with urllib.request.urlopen(f"{BASE}/{name}.geojson") as response:
            rings = rings_of(json.load(response))
        # A ring under three points cannot enclose or outline anything worth drawing.
        rings = [r for r in rings if len(r) >= 3]
        print(f"  {len(rings)} parts, {sum(len(r) for r in rings)} points", file=sys.stderr)
        for ring in rings:
            lines.append(f"{tag} {len(ring)}")
            lines.extend(f"{lon:.4f} {lat:.4f}" for lon, lat in ring)

    with open(out_path, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
