#!/usr/bin/env bash
#
# Regenerates the embedded font headers in src/fonts/.
#
# Run this only when the font sources or the icon set change — the generated
# headers are committed, so a normal build needs neither network nor Python.
#
#   ./tools/generate_fonts.sh
#
# Requirements: curl, a C++ compiler, python3 (a venv with fontTools is created
# under build/fonts/ automatically).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="$REPO_ROOT/build/fonts"
OUT_DIR="$REPO_ROOT/src/fonts"

IMGUI_TAG="v1.92.8"          # same pin as the Makefile — Roboto ships in that tree
FONT_AWESOME_TAG="6.7.2"

# Icons referenced by the UI. Keep in sync with the ICON_FA_* defines in src/ui_theme.hpp.
ICON_CODEPOINTS="U+f00c,U+f00d,U+f013,U+f021,U+f02d,U+f053,U+f060,U+f06a,U+f0c8,U+f111,U+f14a,U+f15c,U+f187,U+f1f8,U+f279,U+f2f2,U+f35d,U+f5b0"

mkdir -p "$WORK_DIR" "$OUT_DIR"
cd "$WORK_DIR"

# ── Sources ───────────────────────────────────────────────────────────────────
[ -f Roboto-Medium.ttf ] || curl -fsSL -o Roboto-Medium.ttf \
    "https://github.com/ocornut/imgui/raw/$IMGUI_TAG/misc/fonts/Roboto-Medium.ttf"
[ -f fa-solid-900.ttf ] || curl -fsSL -o fa-solid-900.ttf \
    "https://github.com/FortAwesome/Font-Awesome/raw/$FONT_AWESOME_TAG/webfonts/fa-solid-900.ttf"
[ -f binary_to_compressed_c.cpp ] || curl -fsSL -o binary_to_compressed_c.cpp \
    "https://github.com/ocornut/imgui/raw/$IMGUI_TAG/misc/fonts/binary_to_compressed_c.cpp"

# ── Tools ─────────────────────────────────────────────────────────────────────
[ -x ./binary_to_compressed_c ] || c++ -O2 -o binary_to_compressed_c binary_to_compressed_c.cpp
[ -x venv/bin/pyftsubset ] || { python3 -m venv venv; ./venv/bin/pip install -q fonttools; }

# ── Subset ────────────────────────────────────────────────────────────────────
# Roboto: Latin-1 is all the UI ever renders (ICAO codes, numbers, English labels).
./venv/bin/pyftsubset Roboto-Medium.ttf \
    --output-file=roboto_subset.ttf \
    --unicodes="U+0020-007E,U+00A0-00FF" \
    --layout-features='' --no-hinting --desubroutinize

./venv/bin/pyftsubset fa-solid-900.ttf \
    --output-file=fa_subset.ttf \
    --unicodes="$ICON_CODEPOINTS" \
    --layout-features='' --no-hinting --desubroutinize

# ── Emit headers ──────────────────────────────────────────────────────────────
emit() {
    local ttf="$1" symbol="$2" header="$3" license="$4"
    {
        echo "// Generated by tools/generate_fonts.sh — do not edit by hand."
        echo "//"
        echo "$license"
        echo "#pragma once"
        echo
        ./binary_to_compressed_c -base85 "$ttf" "$symbol" | sed 's/^static const char/inline const char/'
    } > "$OUT_DIR/$header"
    echo "  $header — $(wc -c < "$OUT_DIR/$header" | tr -d ' ') bytes"
}

emit roboto_subset.ttf roboto_medium roboto_medium.hpp \
"// Roboto Medium, subset to Latin-1.
// Copyright the Roboto Project Authors. Licensed under the Apache License 2.0.
// Source: github.com/ocornut/imgui misc/fonts/Roboto-Medium.ttf ($IMGUI_TAG)
"

emit fa_subset.ttf fa_solid fa_solid.hpp \
"// Font Awesome 6 Free (Solid), subset to the icons used by this plugin.
// Font: SIL OFL 1.1. Icons: CC BY 4.0. Copyright Fonticons, Inc.
// Source: github.com/FortAwesome/Font-Awesome ($FONT_AWESOME_TAG)
"

echo "Font headers written to src/fonts/."
